### ISSUE TITLE
Alguns links

### ISSUE THREAD

**Issue by felipeelia** [learnbr/wordpress#1]
Fala Gustavo! Antes de mais nada, parabéns pela iniciativa! Aqui vão alguns links:

Blog oficial do WordPress.org no Brasil:
https://br.wordpress.org/news/

Blog da equipe brasileira (discussões e avisos):
https://br.wordpress.org/team/

Blogs com conteúdo sobre WordPress:
https://felipeelia.com.br/
https://www.hastedesign.com.br/blog/
https://forma.hastedesign.com.br/blog/
https://mariovalney.com/
https://blog.apiki.com/

Alguns meetups de Comunidade WordPress:
https://meetup.com/pt-BR/wpcuritiba/
https://www.meetup.com/wpsampa/?_locale=pt-BR
https://www.meetup.com/pt-BR/wp-rio/
https://www.meetup.com/pt-BR/Meetup-WordPress-Floripa/
https://www.meetup.com/pt-BR/wp-poa/

Meu canal no YouTube:
https://www.youtube.com/channel/UCD_26rOE3ClALcZreTkyIoQ/

Alguns links em inglês:
https://yoast.com/seo-blog/
https://gutenbergtimes.com/

Precisando de ajuda é só falar!

**Comment by ogustavo-pereira** [comment]
Adicionei todos links no README.md

Obrigado!
